{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "47b260d9_e50d3e5d",
        "filename": "appengine/components/tool_support/gae_sdk_utils.py",
        "patchSetId": 2
      },
      "lineNbr": 606,
      "author": {
        "id": 1351423
      },
      "writtenOn": "2022-01-14T05:33:23Z",
      "side": 1,
      "message": "2Vadim: I changed this back. I have no idea what\u0027s going on but those ModuleFile objects become string types in the lambda so it traces:\n\n  File \"/usr/local/google/home/tikhonov/cr/infra/luci/appengine/components/tool_support/gae_sdk_utils.py\", line 688, in \u003clambda\u003e\n    expanded_yamls.sort(key\u003dlambda x: \u0027\u0027 if x.name \u003d\u003d \u0027default\u0027 else x.name)\n  File \"/usr/local/google/home/tikhonov/cr/infra/luci/appengine/components/tool_support/gae_sdk_utils.py\", line 373, in name\n    return self.data.get(\u0027service\u0027, self.data.get(\u0027module\u0027, \u0027default\u0027))\nAttributeError: \u0027str\u0027 object has no attribute \u0027get\u0027",
      "range": {
        "startLine": 606,
        "startChar": 34,
        "endLine": 606,
        "endChar": 35
      },
      "revId": "26d486dab1d5d2ce1cc7eab3817199ebfcd94284",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}