{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "bdd97419_aaccd44b",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 4
      },
      "lineNbr": 0,
      "author": {
        "id": 1366072
      },
      "writtenOn": "2022-04-21T01:59:47Z",
      "side": 1,
      "message": "I still see some 400 errors. http://screen/4WiihK5ceKHwt32\nShould this error be fixed by this CL?\n\nI deleted Cloud tasks that kept retrying with the error.",
      "revId": "c71a0ee0a3a85486502602f895c59557aed73d9f",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}